"""
A2A data model types — Task, Message, Part, Artifact.

Simplified from the full A2A protobuf schema to Python dataclasses.
Only the fields we need for Tier 1 MVP are included.

Spec reference: https://github.com/a2aproject/A2A/blob/main/docs/specification.md
"""

import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


# Task states per A2A spec
TASK_STATE_SUBMITTED = "submitted"
TASK_STATE_WORKING = "working"
TASK_STATE_COMPLETED = "completed"
TASK_STATE_FAILED = "failed"
TASK_STATE_CANCELED = "canceled"
TASK_STATE_INPUT_REQUIRED = "input-required"

# Terminal states (no further transitions)
TERMINAL_STATES = frozenset({
    TASK_STATE_COMPLETED,
    TASK_STATE_FAILED,
    TASK_STATE_CANCELED,
})


@dataclass
class Part:
    """Smallest content unit in A2A — text, file reference, or structured data."""
    kind: str = "text"  # "text" | "file" | "data"
    text: Optional[str] = None
    file_uri: Optional[str] = None
    file_name: Optional[str] = None
    file_mime_type: Optional[str] = None
    data: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        if self.kind == "text":
            return {"kind": "text", "text": self.text or ""}
        elif self.kind == "file":
            d: Dict[str, Any] = {"kind": "file"}
            if self.file_uri:
                d["file"] = {"uri": self.file_uri}
                if self.file_name:
                    d["file"]["name"] = self.file_name
                if self.file_mime_type:
                    d["file"]["mimeType"] = self.file_mime_type
            return d
        else:
            return {"kind": "data", "data": self.data or {}}


@dataclass
class Message:
    """A communication turn with role and parts."""
    role: str = "user"  # "user" | "agent"
    parts: List[Part] = field(default_factory=list)
    message_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    task_id: Optional[str] = None
    context_id: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {
            "role": self.role,
            "parts": [p.to_dict() for p in self.parts],
            "messageId": self.message_id,
        }
        if self.task_id:
            d["taskId"] = self.task_id
        if self.context_id:
            d["contextId"] = self.context_id
        return d

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Message":
        parts: List[Part] = []
        for p in data.get("parts", []):
            kind = p.get("kind", "text")
            if kind == "text":
                parts.append(Part(kind="text", text=p.get("text", "")))
            elif kind == "file":
                file_info = p.get("file", {})
                parts.append(Part(
                    kind="file",
                    file_uri=file_info.get("uri"),
                    file_name=file_info.get("name"),
                    file_mime_type=file_info.get("mimeType"),
                ))
            elif kind == "data":
                parts.append(Part(kind="data", data=p.get("data", {})))
        return cls(
            role=data.get("role", "user"),
            parts=parts,
            message_id=data.get("messageId", str(uuid.uuid4())),
            task_id=data.get("taskId"),
            context_id=data.get("contextId"),
        )


@dataclass
class Artifact:
    """Output generated by the agent, composed of parts."""
    name: str = "response"
    description: str = ""
    parts: List[Part] = field(default_factory=list)
    artifact_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def to_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {
            "artifactId": self.artifact_id,
            "name": self.name,
            "parts": [p.to_dict() for p in self.parts],
        }
        if self.description:
            d["description"] = self.description
        return d


@dataclass
class Task:
    """Fundamental unit of work in A2A — stateful, identified by unique ID."""
    task_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    context_id: Optional[str] = None
    state: str = TASK_STATE_SUBMITTED
    status_message: Optional[str] = None
    messages: List[Message] = field(default_factory=list)
    artifacts: List[Artifact] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {
            "id": self.task_id,
            "state": self.state,
            "createdAt": self.created_at,
            "updatedAt": self.updated_at,
        }
        if self.context_id:
            d["contextId"] = self.context_id
        if self.status_message:
            d["status"] = {"message": self.status_message}
        if self.messages:
            d["messages"] = [m.to_dict() for m in self.messages]
        if self.artifacts:
            d["artifacts"] = [a.to_dict() for a in self.artifacts]
        return d

    def transition(self, new_state: str, message: Optional[str] = None) -> None:
        """Transition to a new state. Validates terminal states aren't left."""
        if self.state in TERMINAL_STATES and new_state not in TERMINAL_STATES:
            raise ValueError(
                f"Cannot transition from terminal state '{self.state}' to '{new_state}'"
            )
        self.state = new_state
        self.status_message = message
        self.updated_at = time.time()
